### ISSUE TITLE
[FEAT] 관리자 페이지에서 `admin.js`에서 `직원 등록`, `직원 삭제`, `휴가 승인`, `승인 취소` API를 수정합니다.

### ISSUE THREAD

**Issue by bbjbc** [Dev-FE-2/toy-project1-team2-intranet-project#116]
## 📄 Describe

관리자 페이지에서 API를 수정해요.

## ✅ Tasks

- [ ] 사용자 삭제 시 해당 사용자의 출결과 부재 데이터도 함께 삭제되도록 해요.
- [ ] 직원 등록 시 초기 휴가 일수를 10일로 설정해요.
- [ ] 휴가 승인 시 잔여 휴가 일수가 하루 감소해요.
- [ ] 승인 취소 시 잔여 휴가 일수가 하루 증가해요.

## 📋 Ref

추가적인 정보나 참고 문서를 적어요.
