### ISSUE TITLE
[feat] 공지 컴포넌트, 사용자 공지 목록 페이지, 공지 상세 페이지 만들기

### ISSUE THREAD

**Issue by duwlsssss** [Dev-FE-2/toy-project1-team2-intranet-project#23]
## 📄 Describe

공지 컴포넌트, search 컴포넌트, 사용자 공지 목록 페이지, 공지 상세 페이지 만들기

## ✅ Tasks

- [x] components/common/notice/Notice.js
- [x] components/common/notice/Notice.css
- [x] pages/common/user/notice/notice-list/NoticeList.js
- [x] pages/common/user/notice/notice-list/NoticeList.css
- [x] pages/common/user/notice/notice-detail/NoticeDetail.js
- [x] pages/common/user/notice/notice-detail/NoticeDetail.css
