### ISSUE TITLE
[FEAT] 관리자 메인페이지에서 직원목록을 10개만 불러옵니다.

### ISSUE THREAD

**Issue by bbjbc** [Dev-FE-2/toy-project1-team2-intranet-project#24]
## 📄 Describe

관리자 메인페이지에서 `직원 목록`을 불러옵니다. 
10개만 불러와 스크롤이 가능하도록 하고 상세 정보는 직원 관리 페이지로 이동하게 합니다.

## ✅ Tasks

- [x] `axios`를 사용하여 `직원 목록`을 불러옵니다.
- [x] 10개만 잘라 스크롤이 가능하게 합니다.
- [x] 필터링 셀렉트를 통해 `전체`, `수강생`, `매니저`로 나누어 각각에 대해 필터링 되도록 합니다.
- [x] `더 보기` 버튼을 클릭 시 `직원 관리` 페이지로 이동합니다.

## 📋 Ref

![image](https://github.com/user-attachments/assets/7d093d97-bf45-46a5-b954-4ac4b43bcb00)
