### ISSUE TITLE
[FEAT] 관리자 메인 페이지에 공지 게시판을 퍼블리싱합니다.

### ISSUE THREAD

**Issue by bbjbc** [Dev-FE-2/toy-project1-team2-intranet-project#32]
## 📄 Describe

admin 메인 페이지에 있는 공지 게시판을 퍼블리싱합니다.

## ✅ Tasks

- [x] 공지 목록이 가로로 스크롤링 되도록 합니다.
- [x] 공지 게시판을 퍼블리싱합니다.
- [x] `더 보기` 버튼을 누르면 `공지 관리` 페이지로 이동합니다. 

## 📋 Ref

![image](https://github.com/user-attachments/assets/1686cd28-e85e-434b-9ee4-c829cb030966)
