### ISSUE TITLE
[FEAT] 관리자 휴가/공가 관리 페이지를 퍼블리싱합니다.

### ISSUE THREAD

**Issue by bbjbc** [Dev-FE-2/toy-project1-team2-intranet-project#49]
## 📄 Describe

관리자 페이지에서 휴가/공가 관리 페이지를 퍼블리싱합니다.

## ✅ Tasks

- [x] 직원의 모든 휴가/공가 정보를 확인할 수 있습니다.
- [x] 각 휴가 클릭 시 아코디언이 펼쳐지도록 아코디언 ui를 제작합니다.
- [x] 오른쪽 상단에는 휴가 종류 셀렉트, 승인 여부 셀렉트를 삽입합니다.

## 📋 Ref

![image](https://github.com/user-attachments/assets/986356bc-8eb3-4ff7-b1cf-5b08897ac06f)
