### ISSUE TITLE
[FEAT] 관리자 공지 상세 페이지를 퍼블리싱합니다.

### ISSUE THREAD

**Issue by bbjbc** [Dev-FE-2/toy-project1-team2-intranet-project#65]
## 📄 Describe

관리자 공지 상세 페이지를 퍼블리싱합니다.

## ✅ Tasks

- [ ] 사용자 공지 상세 페이지와 동일한 형태입니다.
- [ ] 우측 상단에 `삭제`와 `수정` 버튼을 추가합니다.
- [ ] 공지 관리 페이지에서 공지 클릭 시 상세 페이지로 이동합니다.
- [ ] 메인 페이지에서 공지 클릭 시 상세 페이지로 이동합니다.

## 📋 Ref

![image](https://github.com/user-attachments/assets/93b0035d-0cdd-472d-aa30-08a846591541)
